#############
# Common Defs
#############
version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.7

############
# Workflows
############
workflows:
  version: 2
  example:
    jobs:
      - context-cli-test

##################
# Job Definitions
##################
jobs:
  context-cli-test:
    docker:
      - image: cimg/base:stable
        environment:
          VCS: github
    steps:
      - circleci-cli/install # Installs latest CLI
      - circleci-cli/setup
      - run:
          name: Check other required vars set
          command: |
            [ -z $VCS ] && exit 1 || echo "VCS set, continuing"
      - run:
          name: List current contexts
          command: |
            circleci context list $VCS $CIRCLE_PROJECT_USERNAME
      - run:
          name: Create test context, show again for confirmation
          command: |
            circleci context create $VCS $CIRCLE_PROJECT_USERNAME test-context
            circleci context list $VCS $CIRCLE_PROJECT_USERNAME
      - run:
          name: Show vars in context, should be empty
          command: |
            circleci context show $VCS $CIRCLE_PROJECT_USERNAME test-context
      - run:
          name: Create secret in test context, show again for confirmation
          command: |
            echo "TEST_VALUE" | \
            circleci context store-secret $VCS $CIRCLE_PROJECT_USERNAME test-context TEST_SECRET

            circleci context show $VCS $CIRCLE_PROJECT_USERNAME test-context
      - run:
          name: Remove the secret from the context, show context again to confirm
          command: |
            circleci context remove-secret $VCS $CIRCLE_PROJECT_USERNAME test-context TEST_SECRET
            circleci context show $VCS $CIRCLE_PROJECT_USERNAME test-context
      - run:
          name: Delete test context, show again to confirm
          command: |
            circleci context delete -f $VCS $CIRCLE_PROJECT_USERNAME test-context
            circleci context list $VCS $CIRCLE_PROJECT_USERNAME
          when: always
